[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "adaptive-graph-engine"
version = "0.3.0"

description = "A Python graph engine for dependency modelling, path discovery, graph traversal and relationship-aware analysis."

readme = "README.md"
requires-python = ">=3.11"
license = "MIT"

authors = [
    {name = "Yassine Chaachaa"}
]

[tool.setuptools.packages.find]
where = ["src"]
